os: linux
dist: trusty
sudo: false
language: python
python:
- 2.7
- 3.6
- 3.6-dev
- 3.7-dev
- pypy2.7-5.8.0
- pypy3.5-5.8.0
install:
- pip install --upgrade --force-reinstall "setuptools; python_version != '3.2'" "setuptools
  < 30; python_version == '3.2'"
- pip uninstall --yes apigw-wsgi-handler || true
- pip install --upgrade --force-reinstall --ignore-installed -e .
- pip install pytest
- pip list --format=columns || pip list
script:
- py.test
- echo Checking whether installation flow is not broken...
- pip uninstall --yes apigw_wsgi_handler || true
- pip install --ignore-installed .
- pip list --format=columns || pip list
jobs:
  fast_finish: true
  include:
  - stage: upload new version of python package to PYPI (only for tagged commits)
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        all_branches: true
        python: 3.6
      user: arttii
      distributions: sdist bdist_wheel
      password:
        secure: "Cyxl/vY5kxxW+8qWSbtjq/oTMDpkPVHmu0hSSJ+zIE6XyzRX7bORPkh0M2E3vriSn8supVYPpiW2G834ITE7RgqrWNsyXVEdLTTJjDi6ii2nJnCUFdOjR3lE8ItDYnY6Nms7ZGrkmHBPkhbF2OUVz79ari9LfkS0GBEVgNsnwXia8bMamflVG5E1EO4moUsL4nJzOY7Jy93r7+dUmij1jugxLGxYCgYKdCll0elwO3ruPWR06RVjcfYcXDaNh4SjkqwxOZMIeH1yA7Vkpp76fkzViwsFtF9U45EJ/h4SkWIZiaNw1gl1lgWZI9OY6q5mMhYaQ7kE1B99mqWItijYcRYjCjR9NVr6kYlwb9oetWZ14cv8NzMG8VZYAFA54PEmrqjhMW86bdwhzf21umxo4h8E1ZLjjCvOY3WSZFbdzmiHsEU0fXn5ZuO8EqBQNEiFEz5x6Owv5sOvIpd6E6V9esFS2kOQTUpkOANVOKrW3O4jPiyviOFLuhZacOxXn2iLkqQRXa5UwTmG/n8JkZ0zIXFrrSyGuSOIhV0bfmrbg7c6ylbm5eP5N6Z0Y4OSEMKl9DdIaZi0OjNwmTjw9guneCqZ8RP9J2xI2z00UBeDZAcyJ5WYq2VQa27eYIj3ffay44l84TkzG6ZoRgth48Ic2XLXgl3XsFZ+z6RaSo3c5BA="
cache:
  pip: true
after_failure:
- echo "Here's a list of installed Python packages:"
- pip list --format=columns || pip list
